# Generated by Django 4.0.2 on 2022-03-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_comments_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
    ]
