# Generated by Django 4.0.2 on 2022-03-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_comments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post.jpg', upload_to='posts'),
        ),
    ]
